# Generated by Django 5.0.3 on 2024-03-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='totalRatingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='totalViews',
            field=models.IntegerField(default=0),
        ),
    ]
