# Generated by Django 5.0.3 on 2024-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0004_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('bookId', models.CharField(max_length=100)),
            ],
        ),
    ]
