# Generated by Django 5.0.3 on 2024-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0008_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
