# Generated by Django 5.0.3 on 2024-03-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0010_books_author_books_description_books_imagelink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlyviewedbooks',
            name='bookId',
        ),
        migrations.AddField(
            model_name='recentlyviewedbooks',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageBooks.books'),
        ),
    ]
